
stages: 
  - security
  - build 
  - test

variables:
  BUILD_DIR: "build_${CPP_COMPILER}"
  CMAKE_BUILD_OPTIONS: "-j 4"

include:
  - template: Security/SAST.gitlab-ci.yml

# Set up a Linux build matrix that includes
# information on the image, setup/install
# dependencies, etc
.parallel-linux:
  image: redhat/ubi8
  before_script:
    - dnf update -y && dnf install -y zlib zlib-devel cmake make gcc gcc-c++ clang git python3 
    - git submodule update --init --recursive
  parallel:
    matrix:
      - CPP_COMPILER: g++
        C_COMPILER: gcc

      - CPP_COMPILER: clang++
        C_COMPILER: clang

## The CMake build step
build-linux:
  extends: .parallel-linux
  stage: build
  script:
    - echo "BUILDING $CPP_COMPILER"
    - cmake -B ${BUILD_DIR} . -DCMAKE_CXX_COMPILER=$CPP_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER
    - cmake --build ${BUILD_DIR} $CMAKE_BUILD_OPTIONS 
  artifacts:
    expire_in: 15 mins
    paths:
      - ${BUILD_DIR}

test-linux:
  extends: .parallel-linux
  stage: test
  script:
    - python3 -m pip install -U --force-reinstall pip
    - python3 -m pip install pandas scipy matplotlib
    - echo "TESTING $CPP_COMPILER"
    - cd tests
    - python3 test_cli.py --bin-dir ../${BUILD_DIR}/bin
  artifacts:
    expire_in: 10 days
    when: always
    paths:
      - tests/NFDRSOutput.csv
      - tests/NFDRSIndexes.csv
      - tests/NFDRSMoistures.csv
      - tests/*.png

sast:
  stage: security
  variables:
    SAST_EXCLUDED_PATHS: "build, doc, docs, tests, examples, swig"
