
stages: 
  - security
  - build 
  - test

variables:
  BUILD_DIR: "buid_${COMPILER}"
  CMAKE_BUILD_OPTIONS: "-j 4"

include:
  - template: Security/SAST.gitlab-ci.yml

# Set up a Linux build matrix that includes
# information on the image, setup/install
# dependencies, etc
.parallel-linux:
  image: redhat/ubi8
  before_script:
    - dnf update -y && dnf install -y cmake make gcc gcc-c++ clang git python3 && pip install pandas
    - git submodule update --init --recursive
  parallel:
    matrix:
      - COMPILER: [g++, clang++]

## The CMake build step
build-linux:
  extends: .parallel-linux
  stage: build
  script:
    - echo "BUILDING $COMPILER"
    - cmake -B ${BUILD_DIR} . -DCMAKE_CXX_COMPILER=$COMPILER
    - cmake --build ${BUILD_DIR} $CMAKE_BUILD_OPTIONS 
  artifacts:
    expire_in: 5 mins
    paths:
      - ${BUILD_DIR}

test-linux:
  extends: .parallel-linux
  stage: test
  script:
    - echo "TESTING $COMPILER"
    - cd ${BUILD_DIR}
    python test_cli.py

sast:
  stage: security
  variables:
    SAST_EXCLUDED_PATHS: "build, doc, docs, tests, examples, swig"
